application: ntueatsnakebot
runtime: python
env: flex
api_version: 1
threadsafe: yes
runtime_config:
  python_version: 3

handlers:
- url: .*
  script: eatsnake_lite.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: ssl
  version: latest
